import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { useTheme } from '../context/ThemeContext';

export default function EnvironmentalImpact({ plant }) {
  const { theme } = useTheme();
  const styles = createStyles(theme);
  const raw = plant.environmentalImpact || {};
  const impact = {
    carbonOffset: raw.carbonOffset ?? 0,
    oxygenProduced: raw.oxygenProduced ?? 0,
    treesEquivalent: raw.treesEquivalent ?? 0.01,
  };

  const getProjectedImpact = () => {
    const fullGrowthMultiplier = 10 / Math.max(plant.growthStage ?? 0, 1);
    return {
      carbonOffset: impact.carbonOffset * fullGrowthMultiplier,
      oxygenProduced: impact.oxygenProduced * fullGrowthMultiplier,
    };
  };

  const projected = getProjectedImpact();

  const ImpactCard = ({ icon, label, value, unit, color, description }) => (
    <View style={styles.impactCard}>
      <View style={styles.impactHeader}>
        <Text style={styles.impactIcon}>{icon}</Text>
        <View style={styles.impactInfo}>
          <Text style={styles.impactLabel}>{label}</Text>
          <Text style={styles.impactValue}>
            {value.toFixed(2)} {unit}
          </Text>
        </View>
      </View>
      {description && (
        <Text style={styles.impactDescription}>{description}</Text>
      )}
    </View>
  );

  return (
    <View style={styles.container}>
      <Text style={styles.title}>🌍 Environmental Impact</Text>
      <Text style={styles.subtitle}>
        Your contribution to a greener planet
      </Text>

      <ImpactCard
        icon="🌳"
        label="Carbon Offset"
        value={impact.carbonOffset}
        unit="kg CO₂"
        color={theme.colors.primary}
        description={`Currently offsetting ${impact.carbonOffset.toFixed(2)}kg of carbon dioxide`}
      />

      <ImpactCard
        icon="💨"
        label="Oxygen Produced"
        value={impact.oxygenProduced}
        unit="kg"
        color={theme.colors.water}
        description="Oxygen generated by your plant"
      />

      <ImpactCard
        icon="🌲"
        label="Tree Equivalent"
        value={impact.treesEquivalent}
        unit="trees"
        color={theme.colors.primaryLight}
        description={`Equivalent to ${(impact.treesEquivalent * 100).toFixed(1)}% of a full-grown tree`}
      />

      {plant.growthStage < 10 && (
        <View style={styles.projectionContainer}>
          <Text style={styles.projectionTitle}>📈 Projected Annual Impact</Text>
          <Text style={styles.projectionText}>
            If your plant reaches full maturity, it could offset approximately{' '}
            <Text style={styles.projectionValue}>
              {projected.carbonOffset.toFixed(2)} kg CO₂
            </Text>{' '}
            and produce{' '}
            <Text style={styles.projectionValue}>
              {projected.oxygenProduced.toFixed(2)} kg
            </Text>{' '}
            of oxygen per year!
          </Text>
        </View>
      )}

      <View style={styles.factContainer}>
        <Text style={styles.factTitle}>💡 Did You Know?</Text>
        <Text style={styles.factText}>
          A single tree can absorb up to 22 kg of CO₂ per year. Your plant is
          contributing to cleaner air and a healthier planet! 🌱
        </Text>
      </View>
    </View>
  );
}

const createStyles = (theme) => StyleSheet.create({
  container: {
    backgroundColor: theme.colors.surface,
    padding: 15,
    borderRadius: 10,
    marginVertical: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.text,
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: theme.colors.textSecondary,
    marginBottom: 15,
  },
  impactCard: {
    backgroundColor: theme.colors.surfaceAlt,
    padding: 15,
    borderRadius: 10,
    marginBottom: 12,
  },
  impactHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  impactIcon: {
    fontSize: 32,
    marginRight: 12,
  },
  impactInfo: {
    flex: 1,
  },
  impactLabel: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    marginBottom: 4,
  },
  impactValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.colors.primary,
  },
  impactDescription: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 5,
    fontStyle: 'italic',
  },
  projectionContainer: {
    backgroundColor: theme.colors.surfaceAlt,
    padding: 15,
    borderRadius: 10,
    marginTop: 5,
    marginBottom: 12,
  },
  projectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.colors.primaryDark,
    marginBottom: 8,
  },
  projectionText: {
    fontSize: 12,
    color: theme.colors.primaryDark,
    lineHeight: 18,
  },
  projectionValue: {
    fontWeight: 'bold',
    color: theme.colors.primaryDark,
  },
  factContainer: {
    backgroundColor: '#FFF3E0',
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#FF9800',
  },
  factTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#E65100',
    marginBottom: 5,
  },
  factText: {
    fontSize: 12,
    color: '#F57C00',
    lineHeight: 18,
  },
});

